/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CIndexRouteImport } from './routes/c/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as LlmsFullTxtRouteImport } from './routes/llms-full.txt'
import { Route as KSlugRouteImport } from './routes/k/$slug'
import { Route as CCategoryRouteImport } from './routes/c/$category'

const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullTxtRoute = LlmsFullTxtRouteImport.update({
  id: '/llms-full/txt',
  path: '/llms-full/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KSlugRoute = KSlugRouteImport.update({
  id: '/k/$slug',
  path: '/k/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/c/$category': typeof CCategoryRoute
  '/k/$slug': typeof KSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/c/': typeof CIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/c/$category': typeof CCategoryRoute
  '/k/$slug': typeof KSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/c': typeof CIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/c/$category': typeof CCategoryRoute
  '/k/$slug': typeof KSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/c/': typeof CIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/c/$category'
    | '/k/$slug'
    | '/llms-full/txt'
    | '/llms/txt'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/c/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/c/$category'
    | '/k/$slug'
    | '/llms-full/txt'
    | '/llms/txt'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/c'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/c/$category'
    | '/k/$slug'
    | '/llms-full/txt'
    | '/llms/txt'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/c/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  CCategoryRoute: typeof CCategoryRoute
  KSlugRoute: typeof KSlugRoute
  LlmsFullTxtRoute: typeof LlmsFullTxtRoute
  LlmsTxtRoute: typeof LlmsTxtRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  CIndexRoute: typeof CIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full/txt': {
      id: '/llms-full/txt'
      path: '/llms-full/txt'
      fullPath: '/llms-full/txt'
      preLoaderRoute: typeof LlmsFullTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$slug': {
      id: '/k/$slug'
      path: '/k/$slug'
      fullPath: '/k/$slug'
      preLoaderRoute: typeof KSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  CCategoryRoute: CCategoryRoute,
  KSlugRoute: KSlugRoute,
  LlmsFullTxtRoute: LlmsFullTxtRoute,
  LlmsTxtRoute: LlmsTxtRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  CIndexRoute: CIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
