/**
 * LLM Timeline Data
 *
 * ============================================================================
 * LLM UPDATE INSTRUCTIONS
 * ============================================================================
 * To add a new model, append an object to the `models` array with:
 *   - name: Model name (e.g., "GPT-4o")
 *   - date: Release date as YYYY-MM-DD
 *   - org: Organization (e.g., "OpenAI", "Anthropic", "Google")
 *   - params: Parameter count as string or null (e.g., "175B", "1.8T (MoE)")
 *   - type: "model" for regular models, "milestone" for key events
 *   - license: "open" | "closed" | "partial"
 *   - desc: Brief description
 *
 * To update existing data, find the model by name and modify fields.
 * Data source: https://llm-timeline.com
 * ============================================================================
 */

export interface Model {
  name: string
  date: string // YYYY-MM-DD
  org: string
  params: string | null // e.g., "175B", "1.8T (MoE)"
  type: 'model' | 'milestone'
  license: 'open' | 'closed' | 'partial'
  desc: string
}

export const models: Model[] = [
  {
    name: 'Transformer',
    date: '2017-06-12',
    org: 'Google',
    params: null,
    type: 'milestone',
    license: 'open',
    desc: '\'Attention Is All You Need\' paper introduces the Transformer architecture — the foundation of all modern LLMs.',
  },
  {
    name: 'ELMo',
    date: '2018-02-15',
    org: 'AllenAI',
    params: "0.094B",
    type: 'model',
    license: 'open',
    desc: 'Embeddings from Language Models. Contextualized word representations using bidirectional LSTMs.',
  },
  {
    name: 'GPT-1',
    date: '2018-06-11',
    org: 'OpenAI',
    params: "0.117B",
    type: 'model',
    license: 'open',
    desc: 'First GPT model. Decoder-only transformer demonstrating generative pre-training for language understanding.',
  },
  {
    name: 'BERT',
    date: '2018-10-11',
    org: 'Google',
    params: "0.340B",
    type: 'milestone',
    license: 'open',
    desc: 'Bidirectional Encoder Representations from Transformers. Revolutionized NLP benchmarks and became the foundation for search engines.',
  },
  {
    name: 'GPT-2',
    date: '2019-02-14',
    org: 'OpenAI',
    params: "1.5B",
    type: 'model',
    license: 'open',
    desc: 'Initially withheld due to misuse concerns. Showed emergent text generation quality at scale. \'Too dangerous to release.\'',
  },
  {
    name: 'XLNet',
    date: '2019-06-19',
    org: 'Google / CMU',
    params: "0.340B",
    type: 'model',
    license: 'open',
    desc: 'Generalized autoregressive pretraining. Outperformed BERT on 20 NLP tasks.',
  },
  {
    name: 'RoBERTa',
    date: '2019-07-26',
    org: 'Meta',
    params: "0.355B",
    type: 'model',
    license: 'open',
    desc: 'Robustly Optimized BERT. Showed BERT was significantly undertrained. Achieved new SOTA with better training.',
  },
  {
    name: 'T5',
    date: '2019-10-23',
    org: 'Google',
    params: "11B",
    type: 'milestone',
    license: 'open',
    desc: 'Text-to-Text Transfer Transformer. Unified framework treating all NLP tasks as text generation.',
  },
  {
    name: 'GPT-3',
    date: '2020-05-28',
    org: 'OpenAI',
    params: "175B",
    type: 'milestone',
    license: 'closed',
    desc: '175B parameters. Demonstrated few-shot learning without fine-tuning. Sparked the modern LLM revolution.',
  },
  {
    name: 'GShard',
    date: '2020-06-30',
    org: 'Google',
    params: "600B",
    type: 'model',
    license: 'closed',
    desc: 'First Mixture of Experts model at massive scale. 600B parameters for machine translation.',
  },
  {
    name: 'Switch Transformer',
    date: '2021-01-11',
    org: 'Google',
    params: "1571B",
    type: 'model',
    license: 'open',
    desc: '1.6 trillion parameter MoE model. Demonstrated efficient scaling through sparse expert routing.',
  },
  {
    name: 'Codex',
    date: '2021-08-10',
    org: 'OpenAI',
    params: "12B",
    type: 'milestone',
    license: 'closed',
    desc: 'GPT-3 fine-tuned on code. Powered GitHub Copilot. Proved LLMs could write functional programs.',
  },
  {
    name: 'Megatron-Turing NLG',
    date: '2021-10-11',
    org: 'NVIDIA / Microsoft',
    params: "530B",
    type: 'model',
    license: 'closed',
    desc: '530B parameter dense model. Largest monolithic transformer at its time.',
  },
  {
    name: 'Gopher',
    date: '2021-12-08',
    org: 'DeepMind',
    params: "280B",
    type: 'model',
    license: 'closed',
    desc: '280B parameter model. Extensive analysis of scaling laws and model capabilities across 152 tasks.',
  },
  {
    name: 'LaMDA',
    date: '2022-01-20',
    org: 'Google',
    params: "137B",
    type: 'model',
    license: 'closed',
    desc: 'Language Model for Dialogue Applications. Designed for open-ended conversations. Later became the basis for Bard.',
  },
  {
    name: 'InstructGPT',
    date: '2022-01-27',
    org: 'OpenAI',
    params: "175B",
    type: 'milestone',
    license: 'closed',
    desc: 'Introduced RLHF for alignment. Pioneered the technique of training models to follow human instructions safely.',
  },
  {
    name: 'Chinchilla',
    date: '2022-03-29',
    org: 'DeepMind',
    params: "70B",
    type: 'milestone',
    license: 'closed',
    desc: 'Proved smaller models trained on more data outperform larger undertrained ones. Redefined scaling laws.',
  },
  {
    name: 'PaLM',
    date: '2022-04-04',
    org: 'Google',
    params: "540B",
    type: 'model',
    license: 'closed',
    desc: '540B parameter model. Demonstrated breakthrough capabilities in reasoning, code, and multilingual tasks.',
  },
  {
    name: 'OPT',
    date: '2022-05-03',
    org: 'Meta',
    params: "175B",
    type: 'model',
    license: 'open',
    desc: 'Open Pre-trained Transformer. Meta\'s open-source GPT-3 equivalent. Full model weights released for research.',
  },
  {
    name: 'ChatGLM',
    date: '2022-06-15',
    org: 'Zhipu AI',
    params: "130B",
    type: 'model',
    license: 'open',
    desc: 'First GLM (General Language Model) from Tsinghua-backed Zhipu AI. Bilingual Chinese-English. Autoregressive blank infilling.',
  },
  {
    name: 'BLOOM',
    date: '2022-07-06',
    org: 'BigScience',
    params: "176B",
    type: 'milestone',
    license: 'open',
    desc: 'First 100B+ open-source multilingual model. Built by 1000+ researchers across 70+ countries. 46 languages.',
  },
  {
    name: 'Flan-T5',
    date: '2022-10-20',
    org: 'Google',
    params: "11B",
    type: 'model',
    license: 'open',
    desc: 'Instruction-tuned T5. Demonstrated that instruction tuning dramatically improves task generalization.',
  },
  {
    name: 'ChatGPT',
    date: '2022-11-30',
    org: 'OpenAI',
    params: "175B",
    type: 'milestone',
    license: 'closed',
    desc: 'GPT-3.5 with RLHF in a chat interface. Reached 100M users in 2 months. Defined the AI era.',
  },
  {
    name: 'LLaMA',
    date: '2023-02-24',
    org: 'Meta',
    params: "65B",
    type: 'milestone',
    license: 'partial',
    desc: 'LLaMA 1. Leaked weights ignited the open-source LLM revolution. Showed small models can match GPT-3.',
  },
  {
    name: 'Alpaca',
    date: '2023-03-13',
    org: 'Stanford',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Fine-tuned LLaMA on 52K instructions generated by GPT-3.5. Showed cheap instruction tuning works.',
  },
  {
    name: 'GPT-4',
    date: '2023-03-14',
    org: 'OpenAI',
    params: "~1.8T (MoE)",
    type: 'milestone',
    license: 'closed',
    desc: 'Multimodal (text + vision). Passed the bar exam (90th percentile). Massive leap in reasoning.',
  },
  {
    name: 'Claude 1',
    date: '2023-03-14',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Anthropic\'s first public model. Constitutional AI for safety. 100K context window.',
  },
  {
    name: 'Vicuna',
    date: '2023-03-30',
    org: 'LMSYS',
    params: "13B",
    type: 'model',
    license: 'open',
    desc: 'Fine-tuned LLaMA on ShareGPT conversations. Achieved ~90% of ChatGPT quality. Launched the Chatbot Arena.',
  },
  {
    name: 'StableLM',
    date: '2023-04-19',
    org: 'Stability AI',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Stability AI\'s open-source LLM family. 3B and 7B sizes. Trained on 1.5T tokens. CC-BY-SA license.',
  },
  {
    name: 'StarCoder',
    date: '2023-05-04',
    org: 'BigCode / HuggingFace',
    params: "15.5B",
    type: 'model',
    license: 'open',
    desc: 'Open-source code LLM trained on The Stack (1T tokens, 80+ languages). 8K context. OpenRAIL-M license.',
  },
  {
    name: 'MPT-7B',
    date: '2023-05-05',
    org: 'MosaicML',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Commercially usable open-source model. Trained on 1T tokens. Apache 2.0 license.',
  },
  {
    name: 'PaLM 2',
    date: '2023-05-10',
    org: 'Google',
    params: "340B",
    type: 'model',
    license: 'closed',
    desc: 'Google\'s next-gen model. Powers Bard/Gemini. Improved multilingual, reasoning, and coding capabilities.',
  },
  {
    name: 'Falcon',
    date: '2023-05-25',
    org: 'TII (UAE)',
    params: "180B",
    type: 'model',
    license: 'open',
    desc: 'Trained on 3.5T tokens of RefinedWeb. Topped the Open LLM Leaderboard. Apache 2.0 license.',
  },
  {
    name: 'Orca',
    date: '2023-06-05',
    org: 'Microsoft',
    params: "13B",
    type: 'model',
    license: 'open',
    desc: 'Learned from complex reasoning traces of GPT-4. Progressive learning from teacher models.',
  },
  {
    name: 'Inflection-1',
    date: '2023-06-22',
    org: 'Inflection AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Powers the Pi chatbot. Focused on empathetic, personal AI assistant. Competitive with GPT-3.5.',
  },
  {
    name: 'ChatGLM2',
    date: '2023-06-25',
    org: 'Zhipu AI',
    params: "6B",
    type: 'model',
    license: 'open',
    desc: 'Second generation GLM. 32K context. 42% faster inference. Stronger math and coding capabilities.',
  },
  {
    name: 'Baichuan-7B',
    date: '2023-06-15',
    org: 'Baichuan',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Chinese LLM startup\'s first model. Apache 2.0. Strong Chinese language understanding.',
  },
  {
    name: 'Claude 2',
    date: '2023-07-11',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: '200K context window. Constitutional AI approach. Strong coding and analysis capabilities.',
  },
  {
    name: 'Llama 2',
    date: '2023-07-18',
    org: 'Meta',
    params: "70B",
    type: 'milestone',
    license: 'open',
    desc: 'First truly open-weight large model for commercial use. 7B/13B/70B sizes. RLHF-tuned chat variants.',
  },
  {
    name: 'Code Llama',
    date: '2023-08-24',
    org: 'Meta',
    params: "34B",
    type: 'model',
    license: 'open',
    desc: 'Specialized Llama 2 for code generation. Supports Python, C++, Java, and more. 100K context.',
  },
  {
    name: 'WizardCoder',
    date: '2023-08-26',
    org: 'WizardLM Team',
    params: "34B",
    type: 'model',
    license: 'open',
    desc: 'Evol-Instruct tuned Code Llama. Top open-source coding model of its era. Strong on HumanEval.',
  },
  {
    name: 'Baichuan 2',
    date: '2023-09-06',
    org: 'Baichuan',
    params: "53B",
    type: 'model',
    license: 'open',
    desc: '7B and 13B sizes. Leading Chinese LLM with improved bilingual capabilities. 350K char context.',
  },
  {
    name: 'Qwen',
    date: '2023-09-25',
    org: 'Alibaba',
    params: "72B",
    type: 'model',
    license: 'open',
    desc: 'Alibaba\'s multilingual model series. Strong on Chinese and English tasks. Open weights.',
  },
  {
    name: 'Mistral 7B',
    date: '2023-09-27',
    org: 'Mistral AI',
    params: "7B",
    type: 'milestone',
    license: 'open',
    desc: 'Outperformed Llama 2 70B on all benchmarks despite being smaller. Sliding window attention. Apache 2.0.',
  },
  {
    name: 'Zephyr',
    date: '2023-10-25',
    org: 'HuggingFace',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Mistral 7B fine-tuned with DPO. Showed distilled alignment can match RLHF quality.',
  },
  {
    name: 'ChatGLM3',
    date: '2023-10-27',
    org: 'Zhipu AI',
    params: "6B",
    type: 'model',
    license: 'open',
    desc: 'Third gen GLM. Function calling, code interpreter, and agent capabilities. Open source.',
  },
  {
    name: 'Yi',
    date: '2023-11-02',
    org: '01.AI',
    params: "34B",
    type: 'model',
    license: 'open',
    desc: 'Founded by Kai-Fu Lee. Strong bilingual (English/Chinese) model. Competitive with Llama 2 70B.',
  },
  {
    name: 'Orca 2',
    date: '2023-11-21',
    org: 'Microsoft',
    params: "13B",
    type: 'model',
    license: 'open',
    desc: 'Improved reasoning via careful prompt engineering and synthetic data. Outperforms models 5-10x its size.',
  },
  {
    name: 'Inflection-2',
    date: '2023-11-22',
    org: 'Inflection AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Competitive with GPT-4 on many benchmarks. Second-best LLM at time of release. Powers Pi.',
  },
  {
    name: 'Nous Hermes 2',
    date: '2023-11-13',
    org: 'Nous Research',
    params: "34B",
    type: 'model',
    license: 'open',
    desc: 'Community fine-tuned model on Mistral/Yi. Strong at instruction following. Popular for local AI.',
  },
  {
    name: 'Gemini 1.0',
    date: '2023-12-06',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Google\'s multimodal model family (Nano/Pro/Ultra). Natively multimodal from training.',
  },
  {
    name: 'Mixtral 8x7B',
    date: '2023-12-11',
    org: 'Mistral AI',
    params: "46.7B (MoE)",
    type: 'milestone',
    license: 'open',
    desc: 'Open-source Mixture of Experts. Matched GPT-3.5 quality with only 12.9B active params. Game-changer.',
  },
  {
    name: 'Phi-2',
    date: '2023-12-12',
    org: 'Microsoft',
    params: "2.7B",
    type: 'model',
    license: 'open',
    desc: 'Tiny model matching much larger ones. Demonstrated \'textbook-quality\' data matters more than size.',
  },
  {
    name: 'Gemini 1.0 Ultra',
    date: '2024-02-08',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Most capable Gemini 1.0. Beat GPT-4 on 30/32 benchmarks. Powers Gemini Advanced.',
  },
  {
    name: 'Gemini 1.5 Pro',
    date: '2024-02-15',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: '1 million token context window — 10x previous record. MoE architecture. Processes entire codebases.',
  },
  {
    name: 'Gemma',
    date: '2024-02-21',
    org: 'Google DeepMind',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Google\'s open-source model from Gemini research. 2B and 7B sizes. Strong for its class.',
  },
  {
    name: 'Mistral Large',
    date: '2024-02-26',
    org: 'Mistral AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Mistral\'s first flagship commercial model. 32K context. Top-tier reasoning.',
  },
  {
    name: 'Mistral Small',
    date: '2024-02-26',
    org: 'Mistral AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Cost-efficient commercial model optimized for low-latency. Strong multilingual.',
  },
  {
    name: 'Claude 3',
    date: '2024-03-04',
    org: 'Anthropic',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Haiku/Sonnet/Opus family. Opus matched GPT-4 on most benchmarks. 200K context. Vision.',
  },
  {
    name: 'Inflection-2.5',
    date: '2024-03-07',
    org: 'Inflection AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Competitive with GPT-4 at 40% of compute. Powers Pi chatbot. IQ + EQ focus.',
  },
  {
    name: 'Grok-1',
    date: '2024-03-17',
    org: 'xAI',
    params: "314B (MoE)",
    type: 'model',
    license: 'open',
    desc: 'xAI\'s first open-source model. 314B MoE under Apache 2.0. Largest open MoE at time.',
  },
  {
    name: 'DBRX',
    date: '2024-03-27',
    org: 'Databricks',
    params: "132B (MoE)",
    type: 'model',
    license: 'open',
    desc: 'Open MoE model. 36B active params. Outperformed Llama 2 70B and Mixtral. Apache 2.0.',
  },
  {
    name: 'Jamba',
    date: '2024-03-28',
    org: 'AI21 Labs',
    params: "52B",
    type: 'model',
    license: 'open',
    desc: 'First production Mamba-Transformer hybrid. 256K context. Novel SSM architecture.',
  },
  {
    name: 'Command R+',
    date: '2024-04-04',
    org: 'Cohere',
    params: "104B",
    type: 'model',
    license: 'open',
    desc: 'Optimized for RAG and enterprise. 128K context. 10 languages. Grounded generation.',
  },
  {
    name: 'Reka Core',
    date: '2024-04-15',
    org: 'Reka AI',
    params: "67B",
    type: 'model',
    license: 'closed',
    desc: 'Multimodal (text, image, video, audio). Competitive with GPT-4V. Ex-Google/DeepMind team.',
  },
  {
    name: 'Llama 3',
    date: '2024-04-18',
    org: 'Meta',
    params: "70B",
    type: 'milestone',
    license: 'open',
    desc: 'Trained on 15T tokens. 8B and 70B sizes. New open-source SOTA. Massive community adoption.',
  },
  {
    name: 'Phi-3',
    date: '2024-04-23',
    org: 'Microsoft',
    params: "14B",
    type: 'model',
    license: 'open',
    desc: 'Mini/Small/Medium variants. Phi-3 Mini (3.8B) rivals Mixtral 8x7B. Phone-capable AI.',
  },
  {
    name: 'Snowflake Arctic',
    date: '2024-04-24',
    org: 'Snowflake',
    params: "480B (MoE)",
    type: 'model',
    license: 'open',
    desc: '480B MoE with 17B active. Enterprise-focused. Strong on SQL and coding. Apache 2.0.',
  },
  {
    name: 'DeepSeek V2',
    date: '2024-05-07',
    org: 'DeepSeek',
    params: "236B (MoE)",
    type: 'model',
    license: 'open',
    desc: '236B MoE with only 21B active. Multi-head Latent Attention for efficiency.',
  },
  {
    name: 'GPT-4o',
    date: '2024-05-13',
    org: 'OpenAI',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: '\'Omni\' model. Native audio/vision/text. 2x faster, 50% cheaper than GPT-4 Turbo.',
  },
  {
    name: 'Codestral',
    date: '2024-05-29',
    org: 'Mistral AI',
    params: "22B",
    type: 'model',
    license: 'partial',
    desc: 'Specialized code model. 80+ languages. 32K context. Fill-in-the-middle support.',
  },
  {
    name: 'GLM-4',
    date: '2024-06-05',
    org: 'Zhipu AI',
    params: "9B",
    type: 'model',
    license: 'open',
    desc: 'Open-source GLM-4 series. 128K context. 26 languages. Competitive with Llama 3 8B.',
  },
  {
    name: 'Qwen2',
    date: '2024-06-07',
    org: 'Alibaba',
    params: "72B",
    type: 'model',
    license: 'open',
    desc: 'Major upgrade. 0.5B to 72B range. Competitive with Llama 3 70B. Apache 2.0.',
  },
  {
    name: 'Nemotron-4 340B',
    date: '2024-06-14',
    org: 'NVIDIA',
    params: "340B",
    type: 'model',
    license: 'open',
    desc: 'NVIDIA\'s open model for synthetic data generation. Permissive enterprise license.',
  },
  {
    name: 'DeepSeek Coder V2',
    date: '2024-06-17',
    org: 'DeepSeek',
    params: "236B (MoE)",
    type: 'model',
    license: 'open',
    desc: 'First open MoE code model matching GPT-4 Turbo on coding. 338 programming languages.',
  },
  {
    name: 'Claude 3.5 Sonnet',
    date: '2024-06-20',
    org: 'Anthropic',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Surpassed GPT-4o and Gemini 1.5 Pro. 2x faster than Claude 3 Opus at lower cost.',
  },
  {
    name: 'Gemma 2',
    date: '2024-06-27',
    org: 'Google DeepMind',
    params: "27B",
    type: 'model',
    license: 'open',
    desc: '9B and 27B sizes. Outperforms models 2x its size. Knowledge distillation from Gemini.',
  },
  {
    name: 'InternLM 2.5',
    date: '2024-07-03',
    org: 'Shanghai AI Lab',
    params: "20B",
    type: 'model',
    license: 'open',
    desc: 'Strong reasoning from China\'s national lab. Competitive on math and coding.',
  },
  {
    name: 'Mistral NeMo',
    date: '2024-07-18',
    org: 'Mistral AI / NVIDIA',
    params: "12B",
    type: 'model',
    license: 'open',
    desc: '12B co-developed with NVIDIA. 128K context. Apache 2.0. Drop-in Mistral 7B replacement.',
  },
  {
    name: 'Llama 3.1',
    date: '2024-07-23',
    org: 'Meta',
    params: "405B",
    type: 'milestone',
    license: 'open',
    desc: 'Largest open model — 405B parameters. Matches GPT-4 on many benchmarks. 128K context.',
  },
  {
    name: 'Mistral Large 2',
    date: '2024-07-24',
    org: 'Mistral AI',
    params: "123B",
    type: 'model',
    license: 'open',
    desc: '128K context. Competitive with GPT-4o and Llama 3.1 405B. 12 languages.',
  },
  {
    name: 'Grok-2',
    date: '2024-08-13',
    org: 'xAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Competitive with GPT-4o and Claude 3.5. Available on X platform.',
  },
  {
    name: 'Jamba 1.5',
    date: '2024-08-22',
    org: 'AI21 Labs',
    params: "398B (MoE)",
    type: 'model',
    license: 'open',
    desc: 'Mamba-Transformer hybrid MoE. 94B active. 256K context. Fastest long-context model.',
  },
  {
    name: 'o1-preview',
    date: '2024-09-12',
    org: 'OpenAI',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'First \'reasoning\' model. Chain-of-thought at inference. PhD-level science/math.',
  },
  {
    name: 'Pixtral 12B',
    date: '2024-09-17',
    org: 'Mistral AI',
    params: "12B",
    type: 'model',
    license: 'open',
    desc: 'Built on NeMo architecture with native vision support added. 128K context. Apache 2.0.',
  },
  {
    name: 'Qwen2.5',
    date: '2024-09-19',
    org: 'Alibaba',
    params: "72B",
    type: 'model',
    license: 'open',
    desc: '0.5B to 72B. SOTA open model for coding and math. 18T training tokens.',
  },
  {
    name: 'Palmyra X 004',
    date: '2024-10-09',
    org: 'Writer',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Enterprise LLM. Strong on business writing, RAG, and function calling. Agentic capabilities.',
  },
  {
    name: 'GLM-4-Voice',
    date: '2024-10-15',
    org: 'Zhipu AI',
    params: "9B",
    type: 'model',
    license: 'open',
    desc: 'Open-source end-to-end speech LLM. Understands and generates speech natively. Bilingual.',
  },
  {
    name: 'Ministral',
    date: '2024-10-16',
    org: 'Mistral AI',
    params: "8B",
    type: 'model',
    license: 'open',
    desc: '3B and 8B edge models. Optimized for on-device deployment. 128K context.',
  },
  {
    name: 'SmolLM2',
    date: '2024-11-01',
    org: 'HuggingFace',
    params: "1.7B",
    type: 'model',
    license: 'open',
    desc: 'Tiny but capable. 135M/360M/1.7B sizes. Designed for on-device deployment.',
  },
  {
    name: 'OLMo 2',
    date: '2024-11-20',
    org: 'AllenAI',
    params: "13B",
    type: 'model',
    license: 'open',
    desc: 'Fully open — weights, data, code, training logs. Apache 2.0. Research transparency.',
  },
  {
    name: 'Amazon Nova',
    date: '2024-12-03',
    org: 'Amazon',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Foundation model family: Micro/Lite/Pro/Premier. Multimodal. Optimized for AWS Bedrock.',
  },
  {
    name: 'Llama 3.3',
    date: '2024-12-06',
    org: 'Meta',
    params: "70B",
    type: 'model',
    license: 'open',
    desc: '70B matching Llama 3.1 405B performance. Massive efficiency gain.',
  },
  {
    name: 'Gemini 2.0 Flash',
    date: '2024-12-11',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Multimodal output (text, images, audio). Built for agentic AI. 2x faster than 1.5 Pro.',
  },
  {
    name: 'Phi-4',
    date: '2024-12-12',
    org: 'Microsoft',
    params: "14B",
    type: 'model',
    license: 'open',
    desc: '14B excelling at STEM reasoning. Outperforms much larger models on math.',
  },
  {
    name: 'Gemini 2.0 Flash Thinking',
    date: '2024-12-19',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Experimental reasoning model with visible chain-of-thought. Google\'s answer to o1.',
  },
  {
    name: 'DeepSeek V3',
    date: '2024-12-26',
    org: 'DeepSeek',
    params: "671B (MoE)",
    type: 'milestone',
    license: 'open',
    desc: '671B MoE trained for $5.5M. Matches GPT-4o/Claude 3.5 Sonnet. Revolutionized cost efficiency.',
  },
  {
    name: 'DeepSeek R1',
    date: '2025-01-20',
    org: 'DeepSeek',
    params: "671B (MoE)",
    type: 'milestone',
    license: 'open',
    desc: 'Open-source reasoning model rivaling o1. Pure RL approach. Caused market shockwaves.',
  },
  {
    name: 'Perplexity Sonar',
    date: '2025-02-11',
    org: 'Perplexity AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Search-optimized LLM on Llama 3.3 70B. Real-time web-grounded answers via API.',
  },
  {
    name: 'Grok-3',
    date: '2025-02-17',
    org: 'xAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Trained on Colossus supercluster (100K GPUs). Strong reasoning capabilities.',
  },
  {
    name: 'Claude 3.7 Sonnet',
    date: '2025-02-24',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Hybrid reasoning — toggle instant/extended thinking. Best coding model at launch.',
  },
  {
    name: 'GPT-4.5',
    date: '2025-02-27',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Largest OpenAI model yet. Focus on EQ, creativity, reduced hallucinations.',
  },
  {
    name: 'Gemma 3',
    date: '2025-03-12',
    org: 'Google DeepMind',
    params: "27B",
    type: 'model',
    license: 'open',
    desc: '1B/4B/12B/27B. Multimodal (text+vision). Single GPU. 128K context.',
  },
  {
    name: 'Command A',
    date: '2025-03-13',
    org: 'Cohere',
    params: "111B",
    type: 'model',
    license: 'open',
    desc: 'Cohere\'s 111B flagship. Enterprise RAG, agentic tasks, multilingual. Runs on 2 GPUs.',
  },
  {
    name: 'Nemotron Ultra',
    date: '2025-03-18',
    org: 'NVIDIA',
    params: "253B (MoE)",
    type: 'model',
    license: 'open',
    desc: 'Open reasoning model based on Llama. 253B MoE. Strong enterprise tasks.',
  },
  {
    name: 'Gemini 2.5 Pro',
    date: '2025-03-25',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: '#1 LMArena. Built-in reasoning. 1M context. Best overall model at launch.',
  },
  {
    name: 'Llama 4',
    date: '2025-04-05',
    org: 'Meta',
    params: "400B+ (MoE)",
    type: 'milestone',
    license: 'open',
    desc: 'Scout (109B) and Maverick (400B). 10M token context for Scout. Native multimodal.',
  },
  {
    name: 'GPT-4.1',
    date: '2025-04-14',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Optimized for coding/instruction following. 1M context. 50% cheaper than GPT-4o.',
  },
  {
    name: 'o3',
    date: '2025-04-16',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Full o3 reasoning model. Successor to o1. Deep chain-of-thought.',
  },
  {
    name: 'o4-mini',
    date: '2025-04-16',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Efficient reasoning model. Best cost-performance for coding and STEM.',
  },
  {
    name: 'Zhipu GLM-4.1V',
    date: '2025-04-25',
    org: 'Zhipu AI',
    params: "32B",
    type: 'model',
    license: 'open',
    desc: 'Open 32B and 9B multimodal with reasoning. Competitive on vision tasks.',
  },
  {
    name: 'GLM-4.5',
    date: '2025-07-28',
    org: 'Z.ai',
    params: "355B MoE",
    type: 'model',
    license: 'open',
    desc: 'Z.ai flagship open MoE. 355B total, strong reasoning, coding, and agentic capabilities. Claimed cheaper to run than DeepSeek.',
  },
  {
    name: 'GLM-4.5 Air',
    date: '2025-07-28',
    org: 'Z.ai',
    params: "106B MoE",
    type: 'model',
    license: 'open',
    desc: 'Lightweight variant of GLM-4.5. 106B MoE, efficient inference on 8x H20 GPUs.',
  },
  {
    name: 'GLM-4.5V',
    date: '2025-08-11',
    org: 'Z.ai',
    params: "106B",
    type: 'model',
    license: 'open',
    desc: 'Vision-language model from Z.ai. 106B parameters, strong multimodal understanding.',
  },
  {
    name: 'GLM-4.6',
    date: '2025-10-09',
    org: 'Z.ai',
    params: "Unknown",
    type: 'model',
    license: 'open',
    desc: 'First GLM model with native support for China\'s domestic chips (Cambricon, Moore Threads). FP8 and Int4 quantization.',
  },
  {
    name: 'GLM-4.7',
    date: '2025-12-01',
    org: 'Z.ai',
    params: "Unknown",
    type: 'model',
    license: 'open',
    desc: 'Open-weights model from Z.ai topping global coding and reasoning leaderboards. Includes GLM-4.7 Flash variant.',
  },
  {
    name: 'GLM-5',
    date: '2026-02-11',
    org: 'Z.ai',
    params: "Unknown",
    type: 'model',
    license: 'open',
    desc: 'China\'s first public AI company frontier model. Targets complex systems engineering and long-horizon agentic tasks.',
  },
  {
    name: 'Qwen3',
    date: '2025-04-29',
    org: 'Alibaba',
    params: "235B (MoE)",
    type: 'model',
    license: 'open',
    desc: '0.6B to 235B. Hybrid thinking. 119 languages. 22B active MoE.',
  },
  {
    name: 'Mistral Medium 3',
    date: '2025-05-14',
    org: 'Mistral AI',
    params: "Unknown",
    type: 'model',
    license: 'open',
    desc: 'Front-tier, competitive with GPT-4o. Apache 2.0. Strong multilingual.',
  },
  {
    name: 'Gemini 2.5 Flash',
    date: '2025-05-20',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Cost-efficient reasoning. Controllable thinking depth. #1 Chatbot Arena for speed.',
  },
  {
    name: 'Claude 4 Opus',
    date: '2025-05-22',
    org: 'Anthropic',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Most powerful Anthropic model. Parallel tool use, long autonomous tasks.',
  },
  {
    name: 'Claude 4 Sonnet',
    date: '2025-05-22',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Fast successor to 3.7 Sonnet. Excellent speed-intelligence balance.',
  },
  {
    name: 'MiniMax-M1',
    date: '2025-06-01',
    org: 'MiniMax',
    params: "Unknown",
    type: 'model',
    license: 'open',
    desc: 'Chinese AI lab flagship. Strong long-context. Lightning attention architecture.',
  },
  {
    name: 'Gemini 2.5 Pro (06-05)',
    date: '2025-06-05',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Latest 2.5 Pro. Enhanced coding, reasoning, agentic capabilities.',
  },
  {
    name: 'dots.llm1',
    date: '2025-06-06',
    org: 'Xiaohongshu (RedNote)',
    params: "142B MoE",
    type: 'model',
    license: 'open',
    desc: 'Open-source MoE from RedNote (China\'s Instagram). 142B total, 14B active. Performance on par with frontier models at time of release.',
  },
  {
    name: 'GPT-o3 Pro',
    date: '2025-06-10',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Most powerful OpenAI reasoning model. Extended thinking for frontier problems.',
  },
  {
    name: 'Gemini 2.5 Flash (07-25)',
    date: '2025-07-25',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Latest Flash with improved reasoning, native tool use, enhanced multimodal.',
  },
  {
    name: 'Claude 4.5 Sonnet',
    date: '2025-07-29',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Newest Anthropic model. Improved creative writing, nuance, multi-step reasoning.',
  },
  {
    name: 'Yi-Lightning',
    date: '2024-10-01',
    org: '01.AI',
    params: "Unknown (MoE)",
    type: 'model',
    license: 'closed',
    desc: 'Fast MoE model from Kai-Fu Lee\'s lab. Ranked joint 3rd on LMSYS Arena. Optimized for real-time inference.',
  },
  {
    name: 'Pixtral Large',
    date: '2024-11-17',
    org: 'Mistral AI',
    params: "124B",
    type: 'model',
    license: 'open',
    desc: 'Mistral\'s large multimodal model. 128K context. Native image understanding at scale. Open weights.',
  },
  {
    name: 'Falcon 3',
    date: '2024-12-17',
    org: 'TII (UAE)',
    params: "10B",
    type: 'model',
    license: 'open',
    desc: 'Next-gen Falcon. 1B/3B/7B/10B sizes. Apache 2.0. Enhanced multilingual and multimodal.',
  },
  {
    name: 'Grok 4',
    date: '2025-07-11',
    org: 'xAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'xAI\'s most powerful model. Major reasoning leap. Trained on expanded Colossus cluster.',
  },
  {
    name: 'Grok 4.1',
    date: '2025-11-17',
    org: 'xAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Incremental update to Grok 4. Improved reasoning and instruction following. Available on X and via API.',
  },
  {
    name: 'Grok 4.2',
    date: '2026-02-17',
    org: 'xAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Beta release with rapid learning architecture — improves weekly via user feedback. 256K context, 4-agent parallel reasoning. Medical document analysis added.',
  },
  {
    name: 'Claude Opus 4.1',
    date: '2025-08-05',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Upgrade to Claude 4. Improved coding, instruction following, and tool use.',
  },
  {
    name: 'GPT-5',
    date: '2025-08-07',
    org: 'OpenAI',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Next-generation flagship. Major intelligence leap across coding, math, writing, and reasoning.',
  },
  {
    name: 'GPT-5.1',
    date: '2025-11-12',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Family of four models with adaptive reasoning. Faster, more conversational, improved coding. Rolled out to all ChatGPT users.',
  },
  {
    name: 'GPT-5.2',
    date: '2025-12-11',
    org: 'OpenAI',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Most advanced frontier model for professional work and long-running agents. Family of three models: Pro, Thinking, and base.',
  },
  {
    name: 'Alice AI 1.0',
    date: '2025-10-28',
    org: 'Yandex',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Yandex\'s flagship LLM. First major Russian-developed large language model on the global stage.',
  },
  {
    name: 'Amazon Nova Premier',
    date: '2025-10-31',
    org: 'Amazon',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Most capable Amazon model. 1M context. Multimodal. Teacher for distillation on Bedrock.',
  },
  {
    name: 'Gemini 3 Pro',
    date: '2025-11-18',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: '50%+ improvement over 2.5 Pro. Most powerful Google model. Replaces 2.5 series.',
  },
  {
    name: 'Gemini 3 Deep Think',
    date: '2025-11-18',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Reasoning variant of Gemini 3. Deep chain-of-thought for complex scientific problems.',
  },
  {
    name: 'Gemini 3 Flash',
    date: '2025-12-17',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Fast frontier-class model rivaling larger models at a fraction of the cost. Default model in the Gemini app.',
  },
  {
    name: 'Gemini 3.1 Pro',
    date: '2026-02-19',
    org: 'Google DeepMind',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Google\'s latest flagship. More than doubles reasoning performance over Gemini 3 Pro. Released in preview via Gemini API, AI Studio, and Vertex AI.',
  },
  {
    name: 'Claude Opus 4.5',
    date: '2025-11-24',
    org: 'Anthropic',
    params: "Unknown",
    type: 'milestone',
    license: 'closed',
    desc: 'Anthropic\'s most capable model. 20% accuracy gain. Infinite Chats feature. Excel and financial modeling breakthrough.',
  },
  {
    name: 'Mistral Large 3',
    date: '2025-12-02',
    org: 'Mistral AI',
    params: "41B active (MoE)",
    type: 'model',
    license: 'open',
    desc: 'Sparse MoE with 41B active params. Open weights. Strong reasoning and multilingual.',
  },
  {
    name: 'Sarvam-2B',
    date: '2026-01-15',
    org: 'Sarvam AI',
    params: "2B",
    type: 'model',
    license: 'open',
    desc: 'Indian multilingual LLM. Part of sovereign AI initiative. Supports 10+ Indian languages natively.',
  },
  {
    name: 'Qwen3-Max-Thinking',
    date: '2026-01-27',
    org: 'Alibaba',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Top-tier reasoning model with adaptive tool use. Retrieves information and runs code during inference. Rivals leading frontier models.',
  },
  {
    name: 'Claude Opus 4.6',
    date: '2026-02-05',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Huge leap for agentic planning. Parallel subtask execution, tool and subagent orchestration. Terminal-Bench record.',
  },
  {
    name: 'GPT-5.3-Codex',
    date: '2026-02-05',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Most capable agentic coding model. Available via Codex app, CLI, IDE extensions. Optimized for software engineering.',
  },
  {
    name: 'Mixtral 8x22B',
    date: '2024-04-17',
    org: 'Mistral AI',
    params: "176B (MoE)",
    type: 'model',
    license: 'open',
    desc: 'Large MoE with 8 experts of 22B parameters. Strong multilingual and code performance. Open weights.',
  },
  {
    name: 'WizardLM-2',
    date: '2024-04-15',
    org: 'Microsoft',
    params: "8x22B",
    type: 'model',
    license: 'open',
    desc: 'Advanced instruction-following model family. Multiple sizes including 8x22B variant.',
  },
  {
    name: 'o1-pro',
    date: '2024-12-05',
    org: 'OpenAI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Enhanced reasoning model with more compute for complex tasks. Available in ChatGPT Pro tier.',
  },
  {
    name: 'Inflection 3',
    date: '2024-10-11',
    org: 'Inflection AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Powers Pi chatbot. Strong conversational AI with empathetic dialogue capabilities.',
  },
  {
    name: 'QwQ-32B',
    date: '2025-03-05',
    org: 'Alibaba',
    params: "32B",
    type: 'model',
    license: 'open',
    desc: 'Dedicated reasoning model from Qwen team. Strong mathematical and logical reasoning. Apache 2.0.',
  },
  {
    name: 'Mercury',
    date: '2025-02-26',
    org: 'Inception Labs',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'First commercial diffusion LLM. Novel architecture for faster inference.',
  },
  {
    name: 'Devstral',
    date: '2025-05-21',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Mistral dedicated coding model. Optimized for software engineering and agentic coding tasks.',
  },
  {
    name: 'Seed 1.6',
    date: '2025-06-15',
    org: 'ByteDance',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'ByteDance flagship LLM. Strong general and coding capabilities via API.',
  },
  {
    name: 'Gemma 3n',
    date: '2025-06-26',
    org: 'Google DeepMind',
    params: "4B",
    type: 'model',
    license: 'open',
    desc: 'Efficient on-device model designed for mobile. Runs on phones and edge devices.',
  },
  {
    name: 'Hunyuan A13B',
    date: '2025-06-27',
    org: 'Tencent',
    params: "80B MoE",
    type: 'model',
    license: 'open',
    desc: 'Tencent open MoE model with 80B total, 13B active parameters. Strong multilingual performance.',
  },
  {
    name: 'ERNIE 4.5',
    date: '2025-06-30',
    org: 'Baidu',
    params: "300B MoE",
    type: 'model',
    license: 'open',
    desc: 'Baidu largest model, open-sourced. Multiple sizes including 300B MoE and 21B variants.',
  },
  {
    name: 'LFM2',
    date: '2025-07-10',
    org: 'Liquid AI',
    params: "8B MoE",
    type: 'model',
    license: 'open',
    desc: 'Novel liquid neural network architecture. Efficient MoE design from MIT spinout.',
  },
  {
    name: 'Kimi K2',
    date: '2025-07-11',
    org: 'Moonshot AI',
    params: "1T MoE",
    type: 'milestone',
    license: 'open',
    desc: 'Massive 1T MoE model with open weights. Highly competitive with frontier models. Major Chinese AI milestone.',
  },
  {
    name: 'Qwen3 Coder',
    date: '2025-07-22',
    org: 'Alibaba',
    params: "480B MoE",
    type: 'model',
    license: 'open',
    desc: 'Dedicated coding model from Qwen. 480B MoE architecture with 35B active parameters.',
  },
  {
    name: 'GPT-OSS',
    date: '2025-08-05',
    org: 'OpenAI',
    params: "120B",
    type: 'milestone',
    license: 'open',
    desc: 'OpenAI first open-weight models since GPT-2. 20B and 120B variants. Historic open-source move.',
  },
  {
    name: 'DeepSeek V3.1',
    date: '2025-08-21',
    org: 'DeepSeek',
    params: "671B MoE",
    type: 'model',
    license: 'open',
    desc: 'Major upgrade to V3. Improved reasoning and coding. Open weights.',
  },
  {
    name: 'Hermes 4',
    date: '2025-08-28',
    org: 'NousResearch',
    params: "405B",
    type: 'model',
    license: 'open',
    desc: 'Latest in the Hermes series. Advanced function calling and structured output. Built on Llama 3.1.',
  },
  {
    name: 'Granite 4.0',
    date: '2025-10-02',
    org: 'IBM',
    params: "Unknown",
    type: 'model',
    license: 'open',
    desc: 'IBM open enterprise model. Hybrid Mamba-2 Transformer architecture. Apache 2.0.',
  },
  {
    name: 'MiniMax M2',
    date: '2025-10-23',
    org: 'MiniMax',
    params: "230B MoE",
    type: 'model',
    license: 'open',
    desc: 'Upgraded MiniMax model with improved reasoning and generation. Open weights.',
  },
  {
    name: 'MiniMax M2.5',
    date: '2026-02-12',
    org: 'MiniMax',
    params: "230B MoE",
    type: 'model',
    license: 'open',
    desc: 'Frontier MoE model with 230B total, 10B active. 80.2% on SWE-Bench Verified. Strong coding and agentic capabilities.',
  },
  {
    name: 'Kimi K2.5',
    date: '2025-11-06',
    org: 'Moonshot AI',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Upgraded Kimi model with thinking and reasoning capabilities.',
  },
  {
    name: 'Cogito v2.1',
    date: '2025-11-19',
    org: 'Deep Cogito',
    params: "671B MoE",
    type: 'model',
    license: 'open',
    desc: 'Large 671B MoE reasoning model. Strong on complex tasks.',
  },
  {
    name: 'OLMo 3',
    date: '2025-11-20',
    org: 'Allen AI',
    params: "32B",
    type: 'model',
    license: 'open',
    desc: 'Fully open model with weights, data, and training code. From AI2 research lab.',
  },
  {
    name: 'Nova 2',
    date: '2025-12-02',
    org: 'Amazon',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Amazon next-gen foundation model. Available via AWS Bedrock. Announced at re:Invent.',
  },
  {
    name: 'DeepSeek V3.2',
    date: '2025-12-01',
    org: 'DeepSeek',
    params: "671B MoE",
    type: 'model',
    license: 'open',
    desc: 'Further iteration on V3 series. Enhanced capabilities across all benchmarks.',
  },
  {
    name: 'MiMo V2 Flash',
    date: '2025-12-16',
    org: 'Xiaomi',
    params: "309B MoE",
    type: 'model',
    license: 'open',
    desc: 'Xiaomi large reasoning model. 309B MoE architecture. Strong on math and code.',
  },
  {
    name: 'Molmo 2',
    date: '2025-12-16',
    org: 'Allen AI',
    params: "8B",
    type: 'model',
    license: 'open',
    desc: 'Multimodal model from AI2. Fully open weights, data, and code.',
  },
  {
    name: 'EXAONE 3.5',
    date: '2024-12-09',
    org: 'LG AI Research',
    params: "32B",
    type: 'model',
    license: 'open',
    desc: 'LG AI Research open-source flagship. 32B model listed in Epoch AI Notable AI Models. Strong multilingual and instruction following.',
  },
  {
    name: 'HyperCLOVA',
    date: '2021-02-25',
    org: 'Naver',
    params: "560B",
    type: 'model',
    license: 'closed',
    desc: 'Korea\'s first large-scale LLM. 560B parameters, trained on Korean-heavy corpus. Naver\'s flagship language model.',
  },
  {
    name: 'HyperCLOVA X',
    date: '2023-08-24',
    org: 'Naver',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Naver\'s next-gen LLM optimized for Korean. Launched alongside CLOVA X chatbot. Strong bilingual Korean/English capabilities.',
  },
  {
    name: 'SOLAR 10.7B',
    date: '2023-12-13',
    org: 'Upstage',
    params: "10.7B",
    type: 'model',
    license: 'open',
    desc: 'Korean startup Upstage\'s open model using depth up-scaling. Topped HuggingFace Open LLM Leaderboard at release. Apache 2.0.',
  },
  {
    name: 'SOLAR Pro',
    date: '2024-11-21',
    org: 'Upstage',
    params: "22B",
    type: 'model',
    license: 'closed',
    desc: 'Upstage\'s frontier solar model. 22B parameters with performance rivaling much larger models. Strong on enterprise tasks.',
  },
  {
    name: 'SOLAR 102B',
    date: '2025-12-31',
    org: 'Upstage',
    params: "102B MoE",
    type: 'model',
    license: 'open',
    desc: 'Upstage\'s open 102B MoE model. 12B active parameters. Released as Korea\'s answer to open frontier models.',
  },
  {
    name: 'GPT-Neo',
    date: '2021-03-21',
    org: 'EleutherAI',
    params: "2.7B",
    type: 'model',
    license: 'open',
    desc: 'EleutherAI\'s open replication of GPT-3. First serious open-source GPT-3 alternative. Apache 2.0.',
  },
  {
    name: 'GPT-J',
    date: '2021-06-09',
    org: 'EleutherAI',
    params: "6B",
    type: 'model',
    license: 'open',
    desc: 'First open model runnable on consumer hardware. 6B params, GPT-2 architecture. Widely deployed in early local AI applications.',
  },
  {
    name: 'GPT-NeoX',
    date: '2022-04-14',
    org: 'EleutherAI',
    params: "20B",
    type: 'model',
    license: 'open',
    desc: 'EleutherAI\'s 20B open model — first glimpse that local LLMs could scale to GPT-3 territory. Predecessor to today\'s open-source ecosystem.',
  },
  {
    name: 'Claude Sonnet 4.6',
    date: '2026-02-17',
    org: 'Anthropic',
    params: "Unknown",
    type: 'model',
    license: 'closed',
    desc: 'Most capable Sonnet yet. Full upgrade across coding, computer use, long-context reasoning, agent planning, and design. 1M token context window in beta.',
  },
  {
    name: 'Trinity Large',
    date: '2026-01-27',
    org: 'Arcee AI',
    params: "400B MoE",
    type: 'model',
    license: 'open',
    desc: '400B sparse MoE with only 13B active params. Built in the US, open weights. One of the largest open-source foundation models. Apache 2.0.',
  },
  {
    name: 'Ministral 3',
    date: '2025-12-02',
    org: 'Mistral AI',
    params: "3B/8B/14B",
    type: 'model',
    license: 'open',
    desc: 'Family of 3B, 8B, and 14B edge models — all with vision. Instruct and thinking variants. Small enough for drones, phones, and laptops.',
  },
  {
    name: 'Qwen 3.5',
    date: '2026-02-14',
    org: 'Alibaba',
    params: "397B MoE (17B active)",
    type: 'model',
    license: 'partial',
    desc: 'Agentic AI model from Alibaba. 1M context window, built-in tools for web search, code execution. Qwen3.5-Plus hosted; open weights planned.',
  },
  {
    name: 'Qwen3-Next',
    date: '2025-09-10',
    org: 'Alibaba',
    params: "80B MoE (3B active)",
    type: 'model',
    license: 'open',
    desc: 'Ultra-efficient MoE from Alibaba. 80B total, only 3B active params. Apache 2.0. Strong reasoning with minimal compute.',
  },
  {
    name: 'Falcon H1',
    date: '2025-05-20',
    org: 'TII',
    params: "0.5B–34B",
    type: 'model',
    license: 'open',
    desc: 'Hybrid SSM+attention architecture from UAE Technology Innovation Institute. Six model sizes (0.5B to 34B). Punches above weight class on benchmarks. Apache 2.0.',
  },
  {
    name: 'MiniCPM-o 4.5',
    date: '2026-02-08',
    org: 'OpenBMB',
    params: "9B",
    type: 'model',
    license: 'open',
    desc: 'On-device multimodal LLM from OpenBMB. Full-duplex real-time audio, image, video. Built on Qwen3-8B. Gemini 2.5 Flash level performance at 9B.',
  },
  {
    name: 'Step-3.5-Flash',
    date: '2026-02-01',
    org: 'StepFun',
    params: "196B MoE",
    type: 'model',
    license: 'open',
    desc: 'Open-source sparse MoE from StepFun. 11B active params, 196B total. 100-350 tok/s via 3-way Multi-Token Prediction. Frontier reasoning at low cost.',
  },
  {
    name: 'Mistral Small 2409',
    date: '2024-09-18',
    org: 'Mistral AI',
    params: "22B",
    type: 'model',
    license: 'open',
    desc: 'Updated Mistral Small with improved instruction following. 22B parameters. Apache 2.0.',
  },
  {
    name: 'Mamba Codestral 7B',
    date: '2024-06-16',
    org: 'Mistral AI',
    params: "7B",
    type: 'model',
    license: 'open',
    desc: 'Mamba2 hybrid architecture for code. Efficient long-context code generation. Apache 2.0.',
  },
  {
    name: 'Mistral Small 3.0',
    date: '2025-01-15',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Refreshed Small with state-of-the-art performance at 24B. Apache 2.0.',
  },
  {
    name: 'Mistral Small 3.1',
    date: '2025-03-11',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Adds vision capabilities to Small 3.0. Multimodal, 128K context. Apache 2.0.',
  },
  {
    name: 'Magistral Small',
    date: '2025-06-05',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Mistral reasoning model. Extended thinking, strong STEM performance. Apache 2.0.',
  },
  {
    name: 'Devstral 2',
    date: '2025-12-09',
    org: 'Mistral AI',
    params: "123B",
    type: 'model',
    license: 'partial',
    desc: 'Next-gen coding model. Top SWE-Bench score. Modified MIT license (free unless high revenue).',
  },
  {
    name: 'Devstral Small 2',
    date: '2025-12-09',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Successor to Devstral Small 1, derived from Mistral Small 3.1. Portable coding agent. Apache 2.0.',
  },
  {
    name: 'Magistral Small 1.1',
    date: '2025-07-10',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Improved reasoning performance over Magistral Small. Apache 2.0.',
  },
  {
    name: 'Magistral Small 1.2',
    date: '2025-09-01',
    org: 'Mistral AI',
    params: "24B",
    type: 'model',
    license: 'open',
    desc: 'Adds vision to Magistral Small. Multimodal reasoning model. Apache 2.0.',
  },
  {
    name: 'Magistral Medium',
    date: '2025-06-10',
    org: 'Mistral AI',
    params: "~45B",
    type: 'model',
    license: 'closed',
    desc: 'Frontier-class reasoning model. Extended thinking, strong STEM. Closed API only.',
  },
  {
    name: 'Magistral Medium 1.1',
    date: '2025-07-10',
    org: 'Mistral AI',
    params: "~45B",
    type: 'model',
    license: 'closed',
    desc: 'Improved reasoning performance over Magistral Medium. Closed API only.',
  },
  {
    name: 'Magistral Medium 1.2',
    date: '2025-09-01',
    org: 'Mistral AI',
    params: "~45B",
    type: 'model',
    license: 'closed',
    desc: 'Adds vision to Magistral Medium. Multimodal frontier reasoning. Closed API only.',
  },
]

// Get unique organizations for filter
export const organizations = Array.from(new Set(models.map(m => m.org))).sort()

// Get unique years for grouping
export const years = Array.from(new Set(models.map(m => new Date(m.date).getFullYear()))).sort((a, b) => b - a)
