/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutDuyetbotRouteImport } from './routes/about-duyetbot'
import { Route as CartrackRouteImport } from './routes/cartrack'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FossilRouteImport } from './routes/fossil'
import { Route as LsRouteImport } from './routes/ls'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PProjectRouteImport } from './routes/p/$project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDuyetbotRoute = AboutDuyetbotRouteImport.update({
  id: '/about-duyetbot',
  path: '/about-duyetbot',
  getParentRoute: () => rootRouteImport,
} as any)
const CartrackRoute = CartrackRouteImport.update({
  id: '/cartrack',
  path: '/cartrack',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FossilRoute = FossilRouteImport.update({
  id: '/fossil',
  path: '/fossil',
  getParentRoute: () => rootRouteImport,
} as any)
const LsRoute = LsRouteImport.update({
  id: '/ls',
  path: '/ls',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectRoute = PProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-duyetbot': typeof AboutDuyetbotRoute
  '/cartrack': typeof CartrackRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/fossil': typeof FossilRoute
  '/ls': typeof LsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/p/$project': typeof PProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-duyetbot': typeof AboutDuyetbotRoute
  '/cartrack': typeof CartrackRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/fossil': typeof FossilRoute
  '/ls': typeof LsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/p/$project': typeof PProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-duyetbot': typeof AboutDuyetbotRoute
  '/cartrack': typeof CartrackRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/fossil': typeof FossilRoute
  '/ls': typeof LsRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/p/$project': typeof PProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-duyetbot'
    | '/cartrack'
    | '/contact'
    | '/developers'
    | '/fossil'
    | '/ls'
    | '/privacy'
    | '/projects'
    | '/p/$project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-duyetbot'
    | '/cartrack'
    | '/contact'
    | '/developers'
    | '/fossil'
    | '/ls'
    | '/privacy'
    | '/projects'
    | '/p/$project'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-duyetbot'
    | '/cartrack'
    | '/contact'
    | '/developers'
    | '/fossil'
    | '/ls'
    | '/privacy'
    | '/projects'
    | '/p/$project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutDuyetbotRoute: typeof AboutDuyetbotRoute
  CartrackRoute: typeof CartrackRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  FossilRoute: typeof FossilRoute
  LsRoute: typeof LsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  PProjectRoute: typeof PProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-duyetbot': {
      id: '/about-duyetbot'
      path: '/about-duyetbot'
      fullPath: '/about-duyetbot'
      preLoaderRoute: typeof AboutDuyetbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartrack': {
      id: '/cartrack'
      path: '/cartrack'
      fullPath: '/cartrack'
      preLoaderRoute: typeof CartrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fossil': {
      id: '/fossil'
      path: '/fossil'
      fullPath: '/fossil'
      preLoaderRoute: typeof FossilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ls': {
      id: '/ls'
      path: '/ls'
      fullPath: '/ls'
      preLoaderRoute: typeof LsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project': {
      id: '/p/$project'
      path: '/p/$project'
      fullPath: '/p/$project'
      preLoaderRoute: typeof PProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutDuyetbotRoute: AboutDuyetbotRoute,
  CartrackRoute: CartrackRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  FossilRoute: FossilRoute,
  LsRoute: LsRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  PProjectRoute: PProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
