/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SystemRouteImport } from './routes/system'
import { Route as CatSlugRouteImport } from './routes/$cat.$slug'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const CatSlugRoute = CatSlugRouteImport.update({
  id: '/$cat/$slug',
  path: '/$cat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/subscribe': typeof SubscribeRoute
  '/system': typeof SystemRoute
  '/$cat/$slug': typeof CatSlugRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/subscribe': typeof SubscribeRoute
  '/system': typeof SystemRoute
  '/$cat/$slug': typeof CatSlugRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/subscribe': typeof SubscribeRoute
  '/system': typeof SystemRoute
  '/$cat/$slug': typeof CatSlugRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/subscribe'
    | '/system'
    | '/$cat/$slug'
    | '/api/feed'
    | '/api/mcp'
    | '/api/subscribe'
    | '/category/$slug'
    | '/api/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/subscribe'
    | '/system'
    | '/$cat/$slug'
    | '/api/feed'
    | '/api/mcp'
    | '/api/subscribe'
    | '/category/$slug'
    | '/api/admin/$'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/subscribe'
    | '/system'
    | '/$cat/$slug'
    | '/api/feed'
    | '/api/mcp'
    | '/api/subscribe'
    | '/category/$slug'
    | '/api/admin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  SubscribeRoute: typeof SubscribeRoute
  SystemRoute: typeof SystemRoute
  CatSlugRoute: typeof CatSlugRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$cat/$slug': {
      id: '/$cat/$slug'
      path: '/$cat/$slug'
      fullPath: '/$cat/$slug'
      preLoaderRoute: typeof CatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  SubscribeRoute: SubscribeRoute,
  SystemRoute: SystemRoute,
  CatSlugRoute: CatSlugRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
