/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DataRouteImport } from './routes/data'
import { Route as MailRouteImport } from './routes/mail'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as CatSlugRouteImport } from './routes/$cat.$slug'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiPublicRouteImport } from './routes/api/public'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiSystemRouteImport } from './routes/api/system'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin.$'
import { Route as ApiStoryIdRouteImport } from './routes/api/story.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CatSlugRoute = CatSlugRouteImport.update({
  id: '/$cat/$slug',
  path: '/$cat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoute = ApiPublicRouteImport.update({
  id: '/api/public',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemRoute = ApiSystemRouteImport.update({
  id: '/api/system',
  path: '/api/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryIdRoute = ApiStoryIdRouteImport.update({
  id: '/api/story/$id',
  path: '/api/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/data': typeof DataRoute
  '/mail': typeof MailRoute
  '/mcp': typeof McpRoute
  '/submit': typeof SubmitRoute
  '/subscribe': typeof SubscribeRoute
  '/$cat/$slug': typeof CatSlugRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public': typeof ApiPublicRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/system': typeof ApiSystemRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/story/$id': typeof ApiStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/data': typeof DataRoute
  '/mail': typeof MailRoute
  '/mcp': typeof McpRoute
  '/submit': typeof SubmitRoute
  '/subscribe': typeof SubscribeRoute
  '/$cat/$slug': typeof CatSlugRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public': typeof ApiPublicRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/system': typeof ApiSystemRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/story/$id': typeof ApiStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/data': typeof DataRoute
  '/mail': typeof MailRoute
  '/mcp': typeof McpRoute
  '/submit': typeof SubmitRoute
  '/subscribe': typeof SubscribeRoute
  '/$cat/$slug': typeof CatSlugRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public': typeof ApiPublicRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/system': typeof ApiSystemRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/story/$id': typeof ApiStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/changelog'
    | '/data'
    | '/mail'
    | '/mcp'
    | '/submit'
    | '/subscribe'
    | '/$cat/$slug'
    | '/api/feed'
    | '/api/mcp'
    | '/api/public'
    | '/api/subscribe'
    | '/api/system'
    | '/api/admin/$'
    | '/api/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/changelog'
    | '/data'
    | '/mail'
    | '/mcp'
    | '/submit'
    | '/subscribe'
    | '/$cat/$slug'
    | '/api/feed'
    | '/api/mcp'
    | '/api/public'
    | '/api/subscribe'
    | '/api/system'
    | '/api/admin/$'
    | '/api/story/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/changelog'
    | '/data'
    | '/mail'
    | '/mcp'
    | '/submit'
    | '/subscribe'
    | '/$cat/$slug'
    | '/api/feed'
    | '/api/mcp'
    | '/api/public'
    | '/api/subscribe'
    | '/api/system'
    | '/api/admin/$'
    | '/api/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  DataRoute: typeof DataRoute
  MailRoute: typeof MailRoute
  McpRoute: typeof McpRoute
  SubmitRoute: typeof SubmitRoute
  SubscribeRoute: typeof SubscribeRoute
  CatSlugRoute: typeof CatSlugRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPublicRoute: typeof ApiPublicRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiSystemRoute: typeof ApiSystemRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
  ApiStoryIdRoute: typeof ApiStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$cat/$slug': {
      id: '/$cat/$slug'
      path: '/$cat/$slug'
      fullPath: '/$cat/$slug'
      preLoaderRoute: typeof CatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public': {
      id: '/api/public'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system': {
      id: '/api/system'
      path: '/api/system'
      fullPath: '/api/system'
      preLoaderRoute: typeof ApiSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story/$id': {
      id: '/api/story/$id'
      path: '/api/story/$id'
      fullPath: '/api/story/$id'
      preLoaderRoute: typeof ApiStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  DataRoute: DataRoute,
  MailRoute: MailRoute,
  McpRoute: McpRoute,
  SubmitRoute: SubmitRoute,
  SubscribeRoute: SubscribeRoute,
  CatSlugRoute: CatSlugRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPublicRoute: ApiPublicRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiSystemRoute: ApiSystemRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
  ApiStoryIdRoute: ApiStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
