/**
 * Client-only 3D knowledge graph component.
 *
 * Loads 3d-force-graph and three-spritetext from CDN at runtime.
 * Renders nothing during SSR — the canvas only mounts in the browser.
 * Fetches graph data from /graph-data.json (generated by prebuild).
 */

import { useEffect, useRef, useCallback, useState } from "react";

interface GraphNode {
  id: string;
  label: string;
  url: string;
  type: "article" | "memory";
  group: string;
  tags: string[];
  degree: number;
  // Simulation coordinates injected at runtime by 3d-force-graph
  x?: number;
  y?: number;
  z?: number;
}

interface GraphEdge {
  source: string;
  target: string;
  strong: boolean;
}

interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export function KnowledgeGraph() {
  const rootRef = useRef<HTMLDivElement>(null);
  const mountRef = useRef<HTMLDivElement>(null);
  const [panel, setPanel] = useState<{
    node: GraphNode;
    neighbors: GraphNode[];
  } | null>(null);
  const [legend, setLegend] = useState<{ label: string; color: string }[]>([]);
  const graphRef = useRef<any>(null);
  const nodeByIdRef = useRef<Map<string, GraphNode>>(new Map());
  const adjacencyRef = useRef<Map<string, Set<string>>>(new Map());
  const selectedRef = useRef<string | null>(null);

  const closePanel = useCallback(() => {
    selectedRef.current = null;
    setPanel(null);
    if (graphRef.current) {
      const controls = graphRef.current.controls();
      if (!matchMedia("(prefers-reduced-motion: reduce)").matches) {
        controls.autoRotate = true;
      }
    }
  }, []);

  useEffect(() => {
    const mount = mountRef.current;
    const root = rootRef.current;
    if (!mount || !root) return;

    let destroyed = false;

    const boot = async () => {
      // Dynamic CDN imports — Vite must not resolve these at build time
      const [{ default: ForceGraph3D }, { default: SpriteText }] =
        await Promise.all([
          import(
            /* @vite-ignore */ "https://esm.sh/3d-force-graph@1.73.4"
          ),
          import(
            /* @vite-ignore */ "https://esm.sh/three-spritetext@1.9.4"
          ),
        ]);

      if (destroyed) return;

      let data: GraphData;
      try {
        const res = await fetch("/graph-data.json");
        data = await res.json();
      } catch {
        return;
      }

      if (destroyed) return;

      const nodes = data.nodes.map((n) => ({ ...n }));
      const links = data.edges.map((e) => ({
        source: e.source,
        target: e.target,
        strong: e.strong,
      }));

      const nodeById = new Map<string, GraphNode>(
        nodes.map((n: GraphNode) => [n.id, n]),
      );
      const adjacency = new Map<string, Set<string>>(
        nodes.map((n: GraphNode) => [n.id, new Set<string>()]),
      );
      for (const e of data.edges) {
        adjacency.get(e.source)?.add(e.target);
        adjacency.get(e.target)?.add(e.source);
      }

      nodeByIdRef.current = nodeById;
      adjacencyRef.current = adjacency;

      const prefersReduced = matchMedia(
        "(prefers-reduced-motion: reduce)",
      ).matches;

      const isNear = (node: any) => {
        const sel = selectedRef.current;
        return (
          sel &&
          (node.id === sel || adjacency.get(sel)?.has(node.id))
        );
      };

      const idOf = (ref: any) =>
        typeof ref === "object" ? ref.id : ref;

      // Theme colors from CSS tokens
      const colors = () => {
        const cs = getComputedStyle(document.documentElement);
        const get = (v: string, fallback: string) =>
          cs.getPropertyValue(v).trim() || fallback;
        return {
          node: get("--foreground", "#111"),
          memory: get("--primary", "#197ca8"),
          label: get("--muted-foreground", "#555"),
          accent: get("--primary", "#197ca8"),
          edge: get("--border", "rgba(120,120,120,0.4)"),
        };
      };

      let C = colors();

      // Per-group palette: each article category and each memory type gets a
      // stable distinct hue. Groups are sorted so colors don't shuffle between
      // builds. Falls back to the theme foreground if a group is unmapped.
      const palette = [
        "#6cb2e0", // pastel blue
        "#f2b06a", // pastel amber
        "#8fd49b", // pastel green
        "#ef9a9a", // pastel coral
        "#b9a5e0", // pastel violet
        "#f0d58a", // pastel gold
        "#86d2d6", // pastel teal
        "#f0a8cf", // pastel pink
        "#9fc3ea", // pastel periwinkle
        "#cdd98a", // pastel lime
        "#f0b59a", // pastel peach
        "#a8c7d6", // pastel steel
        "#c9a8e0", // pastel purple
      ];
      const groups = [...new Set(nodes.map((n: GraphNode) => n.group))].sort();
      const groupColor = new Map<string, string>(
        groups.map((g, i) => [g, palette[i % palette.length]]),
      );
      const baseColor = (n: any) => groupColor.get(n.group) ?? C.node;

      // Human-readable legend: strip the `memory:` prefix for display.
      setLegend(
        groups.map((g) => ({
          label: g.replace(/^memory:/, ""),
          color: groupColor.get(g) as string,
        })),
      );

      // Focuses a node: aims the camera at it, opens the detail panel, and
      // locks auto-rotate so the view stays put. Shared by clicks, panel
      // neighbor buttons, and the initial auto-focus. Assigned after Graph
      // is constructed (it closes over Graph).
      let focusOn: (n: any) => void = () => {};

      const Graph = ForceGraph3D({ controlType: "orbit" })(mount)
        .graphData({ nodes, links })
        .backgroundColor("rgba(0,0,0,0)")
        .showNavInfo(false)
        .nodeRelSize(5)
        .nodeVal((n: any) => 1 + (n.degree || 0) * 1.4)
        .nodeResolution(16)
        .nodeOpacity(0.95)
        .nodeColor((n: any) => {
          return selectedRef.current
            ? isNear(n)
              ? C.accent
              : baseColor(n)
            : baseColor(n);
        })
        .nodeThreeObjectExtend(true)
        .nodeThreeObject((n: any) => {
          const showAlways = (n.degree || 0) >= 4;
          const sprite = new SpriteText(n.label);
          sprite.material.depthWrite = false;
          sprite.color =
            selectedRef.current && isNear(n) ? C.accent : C.label;
          // Higher fontSize = sharper canvas texture; textHeight is world size.
          sprite.fontSize = 130;
          sprite.textHeight = 3.4;
          sprite.fontFace = "JetBrains Mono, monospace";
          sprite.fontWeight = "700";
          sprite.padding = 1;
          sprite.strokeWidth = 0;
          sprite.position.y = -8 - (1 + (n.degree || 0) * 1.4);
          sprite.visible =
            showAlways || (selectedRef.current && isNear(n));
          (n as any).__label = sprite;
          return sprite;
        })
        .linkColor((l: any) => {
          const lit =
            selectedRef.current &&
            (idOf(l.source) === selectedRef.current ||
              idOf(l.target) === selectedRef.current);
          return lit ? C.accent : C.edge;
        })
        .linkOpacity(0.45)
        .linkWidth((l: any) => (l.strong ? 1.1 : 0.6))
        .onNodeClick((n: any) => focusOn(n))
        .onNodeHover((n: any) => {
          mount.style.cursor = n ? "pointer" : "grab";
        })
        .onBackgroundClick(() => closePanel());

      focusOn = (n: any) => {
        selectedRef.current = n.id;
        Graph.controls().autoRotate = false;
        const nx = n.x ?? 0;
        const ny = n.y ?? 0;
        const nz = n.z ?? 0;
        const dist = Math.hypot(nx, ny, nz) || 1;
        const r = 1 + 140 / dist;
        Graph.cameraPosition({ x: nx * r, y: ny * r, z: nz * r }, n, 900);
        Graph.nodeColor(Graph.nodeColor());
        Graph.linkColor(Graph.linkColor());
        const neigh = [...(adjacency.get(n.id) || [])]
          .map((id) => nodeById.get(id))
          .filter(Boolean) as GraphNode[];
        setPanel({ node: n, neighbors: neigh });
      };
      // Expose for the React-side focusNode callback (panel neighbor buttons)
      (Graph as any).__focusOn = focusOn;

      Graph.d3Force("charge").strength(-90).distanceMax(220);
      Graph.cooldownTicks(prefersReduced ? 0 : 120);

      const fitFilter = (n: any) => (n.degree || 0) > 0;
      // The "welcome" article is the canonical entry point — focus it once the
      // layout settles. After that, keep the camera put: only re-fit when
      // nothing is selected (so a click-focused node doesn't get yanked back).
      const welcomeNode =
        nodeById.get("welcome") ??
        nodes.find((n: GraphNode) => /welcome/i.test(n.label));
      let didInitialFocus = false;
      Graph.onEngineStop(() => {
        if (!didInitialFocus) {
          didInitialFocus = true;
          if (welcomeNode && !prefersReduced) {
            focusOn(welcomeNode);
            return;
          }
        }
        if (!selectedRef.current) Graph.zoomToFit(700, 40, fitFilter);
      });

      const controls = Graph.controls();
      controls.autoRotate = !prefersReduced;
      controls.autoRotateSpeed = 0.6;
      controls.enableDamping = true;
      controls.dampingFactor = 0.12;
      controls.enableZoom = false;

      // Flat look: drop directional lighting and use full ambient so nodes
      // render as uniform flat discs (no 3D sphere shading) — matches the
      // flat design system.
      for (const obj of Graph.scene().children) {
        if (obj.type === "DirectionalLight") obj.intensity = 0;
        if (obj.type === "AmbientLight") {
          obj.intensity = 1;
          obj.color.set("#ffffff");
        }
      }

      const sizeToContainer = (fit: boolean) => {
        const r = root.getBoundingClientRect();
        Graph.width(r.width).height(r.height);
        if (fit) Graph.zoomToFit(400, 40, fitFilter);
      };

      sizeToContainer(false);
      window.addEventListener("resize", () => sizeToContainer(true));

      // Theme changes -> re-tint
      new MutationObserver(() => {
        C = colors();
        Graph.nodeColor(Graph.nodeColor()).linkColor(Graph.linkColor());
        for (const n of nodeById.values()) {
          if ((n as any).__label) {
            (n as any).__label.color =
              selectedRef.current && isNear(n) ? C.accent : C.label;
          }
        }
      }).observe(document.documentElement, {
        attributes: true,
        attributeFilter: ["class"], // shadcn uses .dark class
      });

      // Pause when off-screen
      new IntersectionObserver((entries) => {
        for (const en of entries) {
          if (en.isIntersecting) Graph.resumeAnimation();
          else Graph.pauseAnimation();
        }
      }, { threshold: 0 }).observe(root);

      graphRef.current = Graph;
    };

    boot();

    return () => {
      destroyed = true;
    };
  }, [closePanel]);

  const focusNode = useCallback((node: GraphNode) => {
    const Graph = graphRef.current;
    // Delegate to the graph-side focus (camera + panel + sticky rotation).
    // The live node object (with x/y/z) lives in the graph, so look it up there.
    const live = Graph?.graphData?.().nodes.find(
      (n: GraphNode) => n.id === node.id,
    );
    Graph?.__focusOn?.(live ?? node);
  }, []);

  return (
    <div
      ref={rootRef}
      className="relative w-full overflow-hidden touch-none"
      style={{ height: "clamp(420px, 70vh, 760px)" }}
    >
      <div
        ref={mountRef}
        className="w-full h-full cursor-grab active:cursor-grabbing"
      />

      <p className="absolute left-2 bottom-2 m-0 font-mono text-[10px] tracking-wider text-muted-foreground pointer-events-none select-none">
        drag to rotate &middot; click a node
      </p>

      {/* Color legend (by category / memory type) */}
      {legend.length > 0 && (
        <ul className="absolute left-2 top-2 m-0 p-0 list-none flex flex-col gap-1 pointer-events-none select-none">
          {legend.map((g) => (
            <li
              key={g.label}
              className="flex items-center gap-1.5 font-mono text-[10px] tracking-wider text-muted-foreground capitalize"
            >
              <span
                className="inline-block w-2 h-2 rounded-full"
                style={{ backgroundColor: g.color }}
              />
              {g.label}
            </li>
          ))}
        </ul>
      )}

      {/* Detail panel */}
      {panel && (
        <aside className="absolute top-0 right-0 w-full sm:w-[360px] h-full p-8 bg-background/88 backdrop-blur-[10px] border-l border-border/40 overflow-y-auto">
          <button
            type="button"
            onClick={closePanel}
            className="absolute top-4 right-4 w-7 h-7 grid place-items-center border-none rounded-full bg-muted text-muted-foreground text-lg leading-none cursor-pointer hover:bg-primary/10 transition-colors"
            aria-label="Close detail"
          >
            &times;
          </button>
          <span className="text-[10px] font-semibold tracking-[0.1em] uppercase text-primary">
            {panel.node.type === "memory" ? "Memory" : "Article"}
          </span>
          <h3 className="text-xl font-bold tracking-tight mt-2 mb-4">
            {panel.node.label}
          </h3>

          {panel.neighbors.length > 0 && (
            <div className="mb-6">
              <span className="block text-[10px] font-semibold tracking-[0.08em] uppercase text-muted-foreground mb-3">
                Connects to
              </span>
              <div className="flex flex-wrap gap-2">
                {panel.neighbors.map((n) => (
                  <button
                    key={n.id}
                    type="button"
                    onClick={() => focusNode(n)}
                    className="font-mono text-[11px] font-medium px-3 py-1 border border-border/50 rounded-full bg-transparent text-muted-foreground cursor-pointer hover:border-primary hover:text-primary hover:bg-primary/5 transition-colors"
                  >
                    {n.label}
                  </button>
                ))}
              </div>
            </div>
          )}

          <a
            href={panel.node.url}
            className="inline-block text-sm font-semibold text-primary"
          >
            Read full entry &rarr;
          </a>
        </aside>
      )}
    </div>
  );
}
