/// <reference types="vite/client" />

declare module "*.svg" {
  const content: string;
  export default content;
}

declare module "*.svg?react" {
  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default content;
}

// Build-time artifact generated by apps/blog/scripts/generate-posts-data.ts.
// Declared so home typechecks succeed even when blog's prebuild hasn't run
// (CI typecheck job, fresh checkouts, etc.). The runtime file is regenerated
// on every blog build.
declare module "*/blog/public/posts-data.json" {
  const data: unknown[];
  export default data;
}
