import { resolve } from "node:path";
import tsconfigPaths from "vite-tsconfig-paths";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [tsconfigPaths()],
  resolve: {
    alias: {
      // apps/blog/public/posts-data.json is generated by the blog build and
      // doesn't exist on CI test runners — alias it to a static fixture so
      // importing src/data/blog-posts.ts never depends on a prior blog build.
      "../../../blog/public/posts-data.json": resolve(
        __dirname,
        "__tests__/fixtures/posts-data.json"
      ),
    },
  },
  test: {
    environment: "node",
    include: ["__tests__/**/*.test.{ts,tsx}"],
  },
});
