/**
 * /llms-full.txt — concatenated raw markdown of all articles for LLM consumption.
 *
 * During production, public/llms-full.txt (generated by scripts/generate-static-files.ts)
 * is served directly by Cloudflare Pages ASSETS.
 * This route provides a dev-mode preview.
 */
import { createFileRoute } from "@tanstack/react-router";
import { getAllArticles } from "../../lib/content";

const SITE_URL = "https://kb.duyet.net";

export const Route = createFileRoute("/llms-full/txt")({
  loader: () => {
    const articles = getAllArticles();

    const lines: string[] = [
      "# duyet.net Knowledge Base — Full Content",
      "",
      `URL: ${SITE_URL}`,
      "",
      "---",
      "",
    ];

    for (const article of articles) {
      lines.push(`# ${article.title}`);
      lines.push(`URL: ${SITE_URL}/k/${article.slug}`);
      lines.push(`Category: ${article.category}`);
      if (article.updated) lines.push(`Updated: ${article.updated}`);
      if (article.summary) lines.push(`Summary: ${article.summary}`);
      lines.push("");
      lines.push(article.raw);
      lines.push("");
      lines.push("---");
      lines.push("");
    }

    return { text: lines.join("\n") };
  },
  head: () => ({
    meta: [{ title: "llms-full.txt | Knowledge Base | duyet.net" }],
  }),
  component: LlmsFullTxtPage,
});

function LlmsFullTxtPage() {
  const { text } = Route.useLoaderData();
  return (
    <main className="mx-auto max-w-4xl px-4 sm:px-6 py-12">
      <pre className="text-xs font-mono whitespace-pre-wrap break-words text-foreground leading-relaxed">
        {text}
      </pre>
    </main>
  );
}
