/**
 * /llms.txt — machine-readable article index for LLM consumption.
 *
 * During production, public/llms.txt (generated by scripts/generate-static-files.ts)
 * is served directly by Cloudflare Pages ASSETS.
 * This route provides a dev-mode preview and documents the shape.
 */
import { createFileRoute } from "@tanstack/react-router";
import { getAllArticles, getAllCategories } from "../../lib/content";

const SITE_URL = "https://kb.duyet.net";

export const Route = createFileRoute("/llms/txt")({
  loader: () => {
    const articles = getAllArticles();
    const categories = getAllCategories();

    const lines: string[] = [
      "# duyet.net Knowledge Base",
      "",
      `URL: ${SITE_URL}`,
      `Sitemap: ${SITE_URL}/sitemap.xml`,
      `Raw Markdown: ${SITE_URL}/k/<slug>.md`,
      "",
      `${articles.length} articles across ${categories.length} categories.`,
      "",
      "## Articles",
      "",
    ];

    for (const article of articles) {
      lines.push(`### ${article.title}`);
      lines.push(`URL: ${SITE_URL}/k/${article.slug}`);
      lines.push(`Category: ${article.category}`);
      if (article.updated) lines.push(`Updated: ${article.updated}`);
      if (article.summary) lines.push(`Summary: ${article.summary}`);
      lines.push("");
    }

    return { text: lines.join("\n") };
  },
  head: () => ({
    meta: [{ title: "llms.txt | Knowledge Base | duyet.net" }],
  }),
  component: LlmsTxtPage,
});

function LlmsTxtPage() {
  const { text } = Route.useLoaderData();
  return (
    <main className="mx-auto max-w-4xl px-4 sm:px-6 py-12">
      <pre className="text-xs font-mono whitespace-pre-wrap break-words text-foreground leading-relaxed">
        {text}
      </pre>
    </main>
  );
}
