/**
 * /robots.txt — crawler directives.
 *
 * During production, public/robots.txt (generated by scripts/generate-static-files.ts)
 * is served directly by Cloudflare Pages ASSETS.
 * This route provides a dev-mode preview.
 */
import { createFileRoute } from "@tanstack/react-router";

const SITE_URL = "https://kb.duyet.net";

const ROBOTS_CONTENT = `User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml

# LLM and AI agent resources
# llms.txt: ${SITE_URL}/llms.txt
# llms-full.txt: ${SITE_URL}/llms-full.txt
`;

export const Route = createFileRoute("/robots.txt")({
  head: () => ({
    meta: [{ title: "robots.txt | Knowledge Base | duyet.net" }],
  }),
  component: RobotsTxtPage,
});

function RobotsTxtPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 sm:px-6 py-12">
      <pre className="text-xs font-mono whitespace-pre-wrap break-words text-foreground leading-relaxed">
        {ROBOTS_CONTENT}
      </pre>
    </main>
  );
}
