/**
 * /sitemap.xml — XML sitemap for search engines.
 *
 * During production, public/sitemap.xml (generated by scripts/generate-static-files.ts)
 * is served directly by Cloudflare Pages ASSETS with the correct Content-Type.
 * This route provides a dev-mode preview.
 */
import { createFileRoute } from "@tanstack/react-router";
import { getAllArticles, getAllCategories } from "../../lib/content";

const SITE_URL = "https://kb.duyet.net";

export const Route = createFileRoute("/sitemap.xml")({
  loader: () => {
    const articles = getAllArticles();
    const categories = getAllCategories();

    const urlEntries: string[] = [
      `  <url>\n    <loc>${SITE_URL}/</loc>\n  </url>`,
      `  <url>\n    <loc>${SITE_URL}/graph</loc>\n  </url>`,
    ];

    for (const cat of categories) {
      urlEntries.push(
        `  <url>\n    <loc>${SITE_URL}/c/${encodeURIComponent(cat)}</loc>\n  </url>`
      );
    }

    for (const article of articles) {
      const lastmod = article.updated
        ? `\n    <lastmod>${article.updated}</lastmod>`
        : "";
      urlEntries.push(
        `  <url>\n    <loc>${SITE_URL}/k/${encodeURIComponent(article.slug)}</loc>${lastmod}\n  </url>`
      );
    }

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries.join("\n")}
</urlset>`;

    return { xml };
  },
  head: () => ({
    meta: [{ title: "sitemap.xml | Knowledge Base | duyet.net" }],
  }),
  component: SitemapPage,
});

function SitemapPage() {
  const { xml } = Route.useLoaderData();
  return (
    <main className="mx-auto max-w-4xl px-4 sm:px-6 py-12">
      <pre className="text-xs font-mono whitespace-pre-wrap break-words text-foreground leading-relaxed">
        {xml}
      </pre>
    </main>
  );
}
