use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use clap::{Args as ClapArgs, Command as ClapCommand, CommandFactory, Subcommand};

use super::{Cli, Ctx};
use crate::domain::ManReport;
use crate::error::CliError;
use crate::output::write_stdout;

const DOC_WIDTH: usize = 100;

const AFTER_HELP: &str = "\
Every artifact is generated from the same clap tree that drives the binary, so it cannot drift from
the real flags. `markdown` and `tree` print to stdout regardless of --json.

Examples:
  duyet docs man --out ./man && man ./man/duyet-config.1
  duyet docs markdown > docs/reference.md
  duyet docs tree | grep posts

JSON (duyet.docs_man.v1, `man` only):
  {\"out\":\"DIR\",\"files\":[\"duyet.1\",\"duyet-posts.1\",...]}";

#[derive(Debug, ClapArgs)]
#[command(after_long_help = AFTER_HELP)]
pub struct Args {
    #[command(subcommand)]
    pub command: DocsCommand,
}

#[derive(Debug, Subcommand)]
pub enum DocsCommand {
    /// Write one roff man page per command
    #[command(after_long_help = AFTER_HELP)]
    Man {
        /// Output directory (created if missing)
        #[arg(long, value_name = "DIR", default_value = "man")]
        out: PathBuf,
    },
    /// Print the Markdown command reference
    #[command(after_long_help = AFTER_HELP)]
    Markdown,
    /// Print every command path, one per line
    #[command(after_long_help = AFTER_HELP)]
    Tree,
}

pub fn run(args: &Args, ctx: &Ctx) -> Result<(), CliError> {
    let mut root = Cli::command().term_width(DOC_WIDTH);
    root.build();
    match &args.command {
        DocsCommand::Man { out } => {
            let mut files = Vec::new();
            write_man(&root, out, &mut files)?;
            ctx.emit(&ManReport {
                out: out.clone(),
                files,
            })
        }
        DocsCommand::Markdown => {
            let mut text = String::new();
            text.push_str("# `duyet` command reference\n\n");
            text.push_str("Generated by `duyet docs markdown` from the clap command tree. ");
            text.push_str(
                "Do not edit by hand; `cargo test -p duyet` fails when this file is stale ",
            );
            text.push_str("and `UPDATE_GOLDEN=1 cargo test -p duyet` rewrites it.\n\n");
            text.push_str("## Command tree\n\n```text\n");
            text.push_str(&tree(&root));
            text.push_str("```\n");
            markdown(&mut root, "duyet", &mut text);
            print_text(&text)
        }
        DocsCommand::Tree => print_text(&tree(&root)),
    }
}

fn print_text(text: &str) -> Result<(), CliError> {
    write_stdout(text.as_bytes())
}

fn visible_subcommands(command: &ClapCommand) -> impl Iterator<Item = &ClapCommand> {
    command
        .get_subcommands()
        .filter(|sub| !sub.is_hide_set() && sub.get_name() != "help")
}

pub fn tree(root: &ClapCommand) -> String {
    let mut out = String::new();
    tree_node(root, "duyet", &mut out);
    out
}

fn tree_node(command: &ClapCommand, path: &str, out: &mut String) {
    let about = command
        .get_about()
        .map(|about| format!("  {about}"))
        .unwrap_or_default();
    out.push_str(&format!("{path}{about}\n"));
    for sub in visible_subcommands(command) {
        tree_node(sub, &format!("{path} {}", sub.get_name()), out);
    }
}

/// The root section documents the global options once; every other node hides its propagated
/// copies so the reference stays one screen per command.
fn markdown(command: &mut ClapCommand, path: &str, out: &mut String) {
    let help = command.render_long_help().to_string();
    out.push_str(&format!(
        "\n## `{path}`\n\n```text\n{}\n```\n",
        help.trim_end()
    ));
    let names: Vec<String> = visible_subcommands(command)
        .map(|sub| sub.get_name().to_owned())
        .collect();
    for name in names {
        if let Some(sub) = command.find_subcommand_mut(&name) {
            let mut sub = std::mem::take(sub).mut_args(|arg| {
                if arg.is_global_set() {
                    arg.hide(true)
                } else {
                    arg
                }
            });
            markdown(&mut sub, &format!("{path} {name}"), out);
        }
    }
}

fn write_man(command: &ClapCommand, dir: &Path, files: &mut Vec<String>) -> Result<(), CliError> {
    let io_err = |path: &Path, source: io::Error| CliError::Io {
        path: path.to_path_buf(),
        source,
    };
    fs::create_dir_all(dir).map_err(|source| io_err(dir, source))?;
    let name = command
        .get_bin_name()
        .unwrap_or_else(|| command.get_name())
        .replace(' ', "-");
    let file = format!("{name}.1");
    let path = dir.join(&file);
    let mut buffer = Vec::new();
    clap_mangen::Man::new(command.clone())
        .render(&mut buffer)
        .map_err(|source| io_err(&path, source))?;
    fs::write(&path, buffer).map_err(|source| io_err(&path, source))?;
    files.push(file);
    for sub in visible_subcommands(command) {
        write_man(sub, dir, files)?;
    }
    Ok(())
}
