/// <reference types="vite/client" />

// Build-time artifact generated by apps/blog/scripts/generate-posts-data.ts.
// Declared so insights typechecks succeed even when blog's prebuild hasn't run
// (CI typecheck job, fresh checkouts, etc.). The runtime file is regenerated
// on every blog build.
declare module "*/blog/public/posts-data.json" {
  const data: unknown[];
  export default data;
}
