/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TagsRouteImport } from "./routes/tags";
import { Route as SeriesRouteImport } from "./routes/series";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as RobotsRouteImport } from "./routes/robots";
import { Route as HtmlSitemapRouteImport } from "./routes/html-sitemap";
import { Route as FeedRouteImport } from "./routes/feed";
import { Route as FeaturedRouteImport } from "./routes/featured";
import { Route as CategoryRouteImport } from "./routes/category";
import { Route as ArchivesRouteImport } from "./routes/archives";
import { Route as AiRouteImport } from "./routes/ai";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TagTagRouteImport } from "./routes/tag/$tag";
import { Route as SeriesSlugRouteImport } from "./routes/series/$slug";
import { Route as CategoryCategoryRouteImport } from "./routes/category/$category";
import { Route as YearMonthSlugRouteImport } from "./routes/$year/$month/$slug";

const TagsRoute = TagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => rootRouteImport,
} as any);
const SeriesRoute = SeriesRouteImport.update({
  id: "/series",
  path: "/series",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const RobotsRoute = RobotsRouteImport.update({
  id: "/robots",
  path: "/robots",
  getParentRoute: () => rootRouteImport,
} as any);
const HtmlSitemapRoute = HtmlSitemapRouteImport.update({
  id: "/html-sitemap",
  path: "/html-sitemap",
  getParentRoute: () => rootRouteImport,
} as any);
const FeedRoute = FeedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => rootRouteImport,
} as any);
const FeaturedRoute = FeaturedRouteImport.update({
  id: "/featured",
  path: "/featured",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoryRoute = CategoryRouteImport.update({
  id: "/category",
  path: "/category",
  getParentRoute: () => rootRouteImport,
} as any);
const ArchivesRoute = ArchivesRouteImport.update({
  id: "/archives",
  path: "/archives",
  getParentRoute: () => rootRouteImport,
} as any);
const AiRoute = AiRouteImport.update({
  id: "/ai",
  path: "/ai",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TagTagRoute = TagTagRouteImport.update({
  id: "/tag/$tag",
  path: "/tag/$tag",
  getParentRoute: () => rootRouteImport,
} as any);
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => SeriesRoute,
} as any);
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: "/$category",
  path: "/$category",
  getParentRoute: () => CategoryRoute,
} as any);
const YearMonthSlugRoute = YearMonthSlugRouteImport.update({
  id: "/$year/$month/$slug",
  path: "/$year/$month/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/ai": typeof AiRoute;
  "/archives": typeof ArchivesRoute;
  "/category": typeof CategoryRouteWithChildren;
  "/featured": typeof FeaturedRoute;
  "/feed": typeof FeedRoute;
  "/html-sitemap": typeof HtmlSitemapRoute;
  "/robots": typeof RobotsRoute;
  "/search": typeof SearchRoute;
  "/series": typeof SeriesRouteWithChildren;
  "/tags": typeof TagsRoute;
  "/category/$category": typeof CategoryCategoryRoute;
  "/series/$slug": typeof SeriesSlugRoute;
  "/tag/$tag": typeof TagTagRoute;
  "/$year/$month/$slug": typeof YearMonthSlugRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/ai": typeof AiRoute;
  "/archives": typeof ArchivesRoute;
  "/category": typeof CategoryRouteWithChildren;
  "/featured": typeof FeaturedRoute;
  "/feed": typeof FeedRoute;
  "/html-sitemap": typeof HtmlSitemapRoute;
  "/robots": typeof RobotsRoute;
  "/search": typeof SearchRoute;
  "/series": typeof SeriesRouteWithChildren;
  "/tags": typeof TagsRoute;
  "/category/$category": typeof CategoryCategoryRoute;
  "/series/$slug": typeof SeriesSlugRoute;
  "/tag/$tag": typeof TagTagRoute;
  "/$year/$month/$slug": typeof YearMonthSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/ai": typeof AiRoute;
  "/archives": typeof ArchivesRoute;
  "/category": typeof CategoryRouteWithChildren;
  "/featured": typeof FeaturedRoute;
  "/feed": typeof FeedRoute;
  "/html-sitemap": typeof HtmlSitemapRoute;
  "/robots": typeof RobotsRoute;
  "/search": typeof SearchRoute;
  "/series": typeof SeriesRouteWithChildren;
  "/tags": typeof TagsRoute;
  "/category/$category": typeof CategoryCategoryRoute;
  "/series/$slug": typeof SeriesSlugRoute;
  "/tag/$tag": typeof TagTagRoute;
  "/$year/$month/$slug": typeof YearMonthSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/ai"
    | "/archives"
    | "/category"
    | "/featured"
    | "/feed"
    | "/html-sitemap"
    | "/robots"
    | "/search"
    | "/series"
    | "/tags"
    | "/category/$category"
    | "/series/$slug"
    | "/tag/$tag"
    | "/$year/$month/$slug";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/ai"
    | "/archives"
    | "/category"
    | "/featured"
    | "/feed"
    | "/html-sitemap"
    | "/robots"
    | "/search"
    | "/series"
    | "/tags"
    | "/category/$category"
    | "/series/$slug"
    | "/tag/$tag"
    | "/$year/$month/$slug";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/ai"
    | "/archives"
    | "/category"
    | "/featured"
    | "/feed"
    | "/html-sitemap"
    | "/robots"
    | "/search"
    | "/series"
    | "/tags"
    | "/category/$category"
    | "/series/$slug"
    | "/tag/$tag"
    | "/$year/$month/$slug";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AiRoute: typeof AiRoute;
  ArchivesRoute: typeof ArchivesRoute;
  CategoryRoute: typeof CategoryRouteWithChildren;
  FeaturedRoute: typeof FeaturedRoute;
  FeedRoute: typeof FeedRoute;
  HtmlSitemapRoute: typeof HtmlSitemapRoute;
  RobotsRoute: typeof RobotsRoute;
  SearchRoute: typeof SearchRoute;
  SeriesRoute: typeof SeriesRouteWithChildren;
  TagsRoute: typeof TagsRoute;
  TagTagRoute: typeof TagTagRoute;
  YearMonthSlugRoute: typeof YearMonthSlugRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tags": {
      id: "/tags";
      path: "/tags";
      fullPath: "/tags";
      preLoaderRoute: typeof TagsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/series": {
      id: "/series";
      path: "/series";
      fullPath: "/series";
      preLoaderRoute: typeof SeriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/robots": {
      id: "/robots";
      path: "/robots";
      fullPath: "/robots";
      preLoaderRoute: typeof RobotsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/html-sitemap": {
      id: "/html-sitemap";
      path: "/html-sitemap";
      fullPath: "/html-sitemap";
      preLoaderRoute: typeof HtmlSitemapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/feed": {
      id: "/feed";
      path: "/feed";
      fullPath: "/feed";
      preLoaderRoute: typeof FeedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/featured": {
      id: "/featured";
      path: "/featured";
      fullPath: "/featured";
      preLoaderRoute: typeof FeaturedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/category": {
      id: "/category";
      path: "/category";
      fullPath: "/category";
      preLoaderRoute: typeof CategoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/archives": {
      id: "/archives";
      path: "/archives";
      fullPath: "/archives";
      preLoaderRoute: typeof ArchivesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ai": {
      id: "/ai";
      path: "/ai";
      fullPath: "/ai";
      preLoaderRoute: typeof AiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tag/$tag": {
      id: "/tag/$tag";
      path: "/tag/$tag";
      fullPath: "/tag/$tag";
      preLoaderRoute: typeof TagTagRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/series/$slug": {
      id: "/series/$slug";
      path: "/$slug";
      fullPath: "/series/$slug";
      preLoaderRoute: typeof SeriesSlugRouteImport;
      parentRoute: typeof SeriesRoute;
    };
    "/category/$category": {
      id: "/category/$category";
      path: "/$category";
      fullPath: "/category/$category";
      preLoaderRoute: typeof CategoryCategoryRouteImport;
      parentRoute: typeof CategoryRoute;
    };
    "/$year/$month/$slug": {
      id: "/$year/$month/$slug";
      path: "/$year/$month/$slug";
      fullPath: "/$year/$month/$slug";
      preLoaderRoute: typeof YearMonthSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface CategoryRouteChildren {
  CategoryCategoryRoute: typeof CategoryCategoryRoute;
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryCategoryRoute: CategoryCategoryRoute,
};

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren
);

interface SeriesRouteChildren {
  SeriesSlugRoute: typeof SeriesSlugRoute;
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSlugRoute: SeriesSlugRoute,
};

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  ArchivesRoute: ArchivesRoute,
  CategoryRoute: CategoryRouteWithChildren,
  FeaturedRoute: FeaturedRoute,
  FeedRoute: FeedRoute,
  HtmlSitemapRoute: HtmlSitemapRoute,
  RobotsRoute: RobotsRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRouteWithChildren,
  TagsRoute: TagsRoute,
  TagTagRoute: TagTagRoute,
  YearMonthSlugRoute: YearMonthSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
