name: Checks

on:
  workflow_call:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v6
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec turbo check-types

      - name: Test
        run: pnpm run test
        env:
          NODE_ENV: test
          CI: true

      - name: Lint
        run: pnpm run lint

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-coverage
          path: |
            **/coverage
          retention-days: 7
          if-no-files-found: ignore
